experiment:
  name: baseline_lovif_constant_ema
  prompt: remove degradation

paths:
  json_dir: /home/student_1/LoViF/FUMO/json
  train_jsonl: baseline_train.jsonl
  validation_jsonl: /home/student_1/LoViF/FUMO/json/baseline_val.jsonl
  output_dir: /home/student_1/LoViF/FUMO/outputs

split:
  type: gt_based
  val_ratio: 0.05
  seed: 42

sampling:
  strategy: lovif_only_all_lq

stage1:
  pretrained_model_name_or_path: Manojb/stable-diffusion-2-1-base
  resolution: 768
  train_batch_size: 1
  gradient_accumulation_steps: 2
  learning_rate: 2.0e-5
  max_train_steps: 100000
  checkpointing_steps: 2000
  log_interval: 100
  checkpoints_total_limit: 3
  validation_steps: 2000
  num_validation_images: 1
  validation_example_index: 0
  dataloader_num_workers: 4
  mixed_precision: bf16
  report_to: none
  tracker_project_name: fumo_baseline
  lr_scheduler: constant
  lr_warmup_steps: 0
  beta_max: 0.25
  beta_warmup_ratio: 0.1
  shrink_prob: 0.1
  use_controlnet_ema: true
  use_unet_ema: true
  ema_decay: 0.999
  use_m_local_diffusion: false
  m_local_lambda: 0.5
  m_local_missing_policy: error
  seed: 42
  enable_xformers_memory_efficient_attention: false
  gradient_checkpointing: true
